### ISSUE TITLE
Need definition of performance model

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#21] opened 2017-04-28 14:17 UTC
Both CWMNX and GMNX share a common notion of a performance model, which can be synthesized for audio presentation to a user.

At present, this model consists of note-style events that have some simple, MIDI-like attributes: instrument sound, pitch, dynamics, onset, duration, and a vague notion of "techniques" that presumably modify the sonic characteristics.

We need to decide exactly what an MNX-compliant implementation may or must do with these events. Here are at least some of the questions in play:

- How do pitches map to sounds on unpitched instruments? Percussion mappings are particularly problematic.

- What are the supported techniques for different instruments (e.g _spiccato_, _col legno_ for violin) and how will they be encoded?

**Comment by cecilios** [comment] 2017-10-06 16:16
I'm not sure if this issue includes playback repetitions for CWMNX.

In the MusicXML model playback repetition is controlled by different elements: 
- the &lt;repeat&gt; element and the &lt;ending&gt; element in &lt;barline&gt;
- attributes segno and coda of the &lt;barline&gt; element
- attributes dacapo, coda, tocoda, segno, dalsegno, forward-repeat, fine, divisions and times-only of the &lt;sound&gt; element.

But there are some problems. In MusicXML, the &lt;repeat&gt; and &lt;ending&gt; elements in  &lt;barline&gt; serve at the same time for two purposes: visual (volta brackets and dots in barlines) and sound (controlling playback repetitions).

But in other cases the visual and sound roles are separated: i.e.: the repeat attributes in the sound element (coda/tocoda, segno/dalsegno) are only for playback, and should be paired with the corresponding visual elements by using a &lt;direction&gt; element. As many people use notation programs just to make things look right, not to play correctly, they only include the visual elements, and this forces MusicXML importers to do inferences for playback from MusicXML visual elements, in order match both models (visual and sound).

As this is always expected, what is the purpose of separating the visual and sound aspects of repetitions? In fact, in MusicXML the visual and playback aspects of repetition elements in barlines are not separated. But are separated in repetition marks (segno, coda, etc.) thus allowing to create inconsistencies between the visual and the playback model for segno / coda structures.

Should CWMNX review this?

**Comment by cecilios** [comment] 2017-10-07 18:43
Just to clarify my concerns:

- Why to separate visual information from sound information for playback repetitions if playback must always follow the path implied by the visual representation (any counter example, apart from rehearsals and study?).

- Assuming that there exist valid cases in which visual information about repetitions differ from the desired playback path, the problem is that there is nothing saying that this mismatch is on purpose. Without an 'on purpose' explicit indication, the visual / sound separation is useless for repetitions. For instance, currently most MusicXML importers will always assume that the outmatch is due to a bad MusicXML exporter or to a careless user that only paid attention to get a good looking score for printing. As a consequence a lot of burden is placed on MusicXML importers for matching both models. And worse: any on purpose outmatch will be 'fixed' by the importer, making the visual/sound separation useless.

In my opinion this should be addressed in CWMNX. Some ideas:

- Do not split visual and sound roles for repetitions (coda, segno, etc.), as playback must always follow the path implied by the visual representation. The only scenarios I can think are rehearsals and study. In these scenarios, sometimes repetitions are not performed.

- If CWMNX would like to support those scenarios, then the visual/sound aspects of barline ending/repeat elements have to be split, so that the 'conductor'/'student' can explicitly indicate the sound path by  disabling certain sound elements.

- If the visual/sound roles are finally split and kept, either:
	- Enforce the sound and visual models to match. CWMNX readers will always do playback guided by sound elements and users will always be able to control the playback path by enabling/disabling the sound elements controlling the playback path. Or 
	- Introduce an global explicit element to indicate whether mismatches in a file are on purpose or not, to instruct CWMNX readers on how to behave (fix or not fix them). Or
	- Clearly state that CWMNX readers must not fix any mismatch between the sound and the visual elements, for preventing to destroy any on purpose effect.

**Comment by joeberkovitz** [comment] 2017-10-13 15:15
@cecilios Let's start with the playback order question in your first comment https://github.com/w3c/mnx/issues/21#issuecomment-334801666

Definitely performance order or measures must be part of the playback model. I would expect this to be driven by default by <repeat>, <barline>, <ending>, and other elements that are semantic in character (i.e., have an agreed musical meaning in CWMN which has both visual and playback consequences). Also, some additional cleanup needs to take place in CWMNX to allow purely textual descriptions like `<words>D.C. al fine</words>` to be flagged as having the specific semantics of _da capo al fina_, etc. so that applications are not obliged to reverse-engineer these meanings from the text, as is so often the case in MusicXML today. I think this is a better approach than duplicating such directions in a `<sound>` element. The guiding principle is this: where it is possible to have a single, unified description of a formal element that has both visual and playback consequences CWMNX should permit that to happen. In MusicXML that's already the case with things like `<repeat>`, but it doesn't work with things like _D.C. al fine_ text.

I would prefer to see the use of playback-only specifiers like `<sound>` come into play only when the default interpretation of  is being overridden. In such cases, it seems best to me that the encoding provide a low-level, explicit performance order (e.g. "perform the following range of music by playing this exact list of measures") and not create a different, potentially overlapping set of coda/segno/ending type instructions.

**Comment by joeberkovitz** [comment] 2017-10-13 15:22
On to the second more general comment https://github.com/w3c/mnx/issues/21#issuecomment-334957437

> Why to separate visual information from sound information for playback repetitions if playback must always follow the path implied by the visual representation (any counter example, apart from rehearsals and study?).

In general, we should avoid such separation, as I responded above. It does need to occur sometimes when semantic notations just don't contain enough information. But CWMNX will reduce the number of such cases by allowing more textual directions to be given a definite meaning.

> Assuming that there exist valid cases in which visual information about repetitions differ from the desired playback path, the problem is that there is nothing saying that this mismatch is on purpose. 

I agree. In CWMNX, explicit playback information should be reserved entirely for the case where the producer of the document explicitly intends for the playback to differ from the default interpretation of the semantic/visual facets.

**Comment by cecilios** [comment] 2017-10-14 11:11
@joeberkovitz Thanks for your comments.

> The guiding principle is this: where it is possible to have a single, unified description of a formal element that has both visual and playback consequences CWMNX should permit that to happen.

> I would prefer to see the use of playback-only specifiers like <sound> come into play only when the default interpretation of is being overridden. In such cases, it seems best to me that the encoding provide a low-level, explicit performance order (e.g. "perform the following range of music by playing this exact list of measures") and not create a different, potentially overlapping set of coda/segno/ending type instructions.

I fully agree with your ideas.

**Comment by joeberkovitz** [comment] 2018-04-25 20:32
Note that the playback ordering questions are now handled in issue #99

**Comment by adrianholovaty** [comment] 2021-12-07 16:33
(Closing this issue because MNX-Generic is no longer in scope for our community group.)

**Closed by adrianholovaty** 2021-12-07 16:33 UTC
Labels: MNX-Generic, design
