### ISSUE TITLE
Clarification of the roles to be played by MNX, CWMNX and GMNX

### ISSUE THREAD

**Issue by notator** [w3c/mnx#23] opened 2017-04-30 09:00 UTC
Can we agree that:
CWMNX is intended to be an improvement on, and replacement for MusicXML.
GMNX is intended to describe a score instantiation that contains both spatial (SVG) and performance information. (And that GMNX is not a dialect of CWMNX)
MNX is intended as a container, that can contain related CWMNX and GMNX code. If MNX has other functions, please explain.

I think the latest version of the MNX Proposal Overview (20 April 2017) needs updating. In particular, §1 needs to explain that MNX is a container format.

**Comment by joeberkovitz** [comment] 2017-04-30 15:35
Your understandings of CWMNX and GMNX are correct, and the proposal should be clarified.

However, "MNX" is intended to refer to the entire ensemble of encodings here, not only to the container format. So we may need a more specific term to refer to the container part of MNX.

**Comment by notator** [comment] 2017-05-01 19:13
I don't understand why we need a container part of MNX. Can you provide a use-case? Thanks.

**Comment by joeberkovitz** [comment] 2017-05-08 14:02
There are several motivations for the container feature:

- Use case https://w3c.github.io/mnx/use-cases/#MP15 (Publisher wants to encode a organized collection of works in a single document)
- The ability to package one or more appropriate encodings for a work in a standard fashion
- The ability to provide descriptive metadata in a standard way that is independent of encoding choice

There is no reason that CWMNX/GMNX can't exist as a separate file, and the container feature as proposed already allows the contents to be broken out as separate files (see https://w3c.github.io/mnx/overview/#inclusion-by-reference which is not very clear, but that's the intention). The container idea is not really so much about putting everything into a single file, although that is sometimes useful.

I think the separate-vs-unified packaging question needs to be discussed in its own right.

**Comment by joeberkovitz** [comment] 2018-01-09 19:22
The new specification attempts to clarify these roles and differences.

**Comment by notator** [comment] 2018-01-14 12:32
I'm still not convinced that we need the MNX container format.

Here, for reference, is how our [Group Charter](https://www.w3.org/community/music-notation/wiki/Group_Charter) currently defines MNX, CWMNX and GMNX:
> The MNX specification itself consists of three parts:
>
> -- The MNX container format, which can describe and relate an arbitrary number of components and documents which collectively describe a notated work as a whole.
>
> -- The CWMNX format (working title), designed to represent Common Western Music Notation in a tightly specified, semantic fashion in order to deliver a high degree of interoperability between a broad range of applications that require such a representation. CWMNX is designed to leverage as much as possible of the existing MusicXML schema.
>
> -- The GMNX format (working title), designed to represent instantiations of scores in terms of specific visual, performance and audio content and a set of relationships between these facets. GMNX aims to supply a high degree of interoperability to applications that do not depend on particular notational systems or their semantics.

The charter says nothing about how the MNX specification is going to implement the three formats. In particular, it says nothing about having to implement them using `<mnx>`, `<cwmnx>` and `<gmnx>` container tags.

MNX: The standard way to package related documents is to put them in (nested) folders. That's true both on web sites, on private computers and when delivering commercial or academic documents offline. If everyone had their own format for packaging, nobody would be able to open anything. Standard folders are the solution for all the use-cases mentioned above.

GMNX: The standard way to put related audio and image files in a document is to use HTML. As an example that replaces `<gmnx>` by `<html>` and `<svg>`, see my [oggPngPlayer](http://james-ingram.de/demos/scoreAudioSynchDemo/oggPng.html). This duplicates the behaviour of @joeberkowitz's [GMNX viewer](https://joeberkovitz.github.io/gmnx-viewer/) playing the Lutoslawski example. This means that the `<gmnx>` container tag is redundant. GMNX can be implemented in terms of existing standards.

CWMNX: My proposal (Issue #25) is that standard SVG should be used, but with an agreed class and class-nesting structure. The proposal, which uses `<svg>` instead of `<cwmnx>`, has the additional advantage of being extensible. Semantically rich definitions of any other music notation can be added as necessary, so the proposal also covers non-CWMN scores (i.e. semantically rich "GMNX"). The `<cwmnx>` tag is redundant because CWMNX can be implemented using `<svg>`.
The Group Charter says
> CWMNX is designed to leverage as much as possible of the existing MusicXML schema.

It would be great if the MusicXML community would help design a standard class and class nesting structure for the CWMN dialect of the MNX specification.

**Comment by joeberkovitz** [comment] 2018-03-05 18:52
The co-chairs have now reviewed this issue and feel it should be closed. Despite the fact that it would be most easily structured as three separate issues, we'd like to respond to all three facets at the same time in the interest of keeping the discussion more compact, and our reasons for recommending closure are not the same in each case.

With respect to the MNX container: Folders alone do not replace the Container schema because 1) a directory structure does not capture the nuances of and relationships between component files, 2) a directory structure does not encode global data about the overall collection of components, 3) on the web, directory contents cannot be enumerated, 4) web standards (including HTML and SVG) universally favor a graph structure for collections of related resources, over a hierarchical directory structure which is merely a special case of a graph. We are closing this topic because the counterproposal doesn't appear to support these basic requirements. 

With respect to GMNX: The ability to implement a GMNX viewer in HTML, does not mean that HTML replaces GMNX. GMNX is an encoding, not an application; as such, GMNX captures data rather than any specific behavior pertaining to that data. Thus, GMNX supports a large family of alternative use cases not limited to music viewers, for instance [RLP11](https://w3c.github.io/mnx/use-cases/#RLP11) to name one. We are closing this topic because of the apparent misunderstanding of GMNX as a type of web-based experience of music, rather than as an encoding.

Regarding CWMNX: #25 has been closed, so this topic is being closed as a duplicate of a closed issue.

**Closed by joeberkovitz** 2018-03-05 18:52 UTC
